// src/app/about/about.component.ts
import {Component} from '@angular/core';

@Component({
    selector: 'about',
    templateUrl: 'about.component.html'
})
export class AboutComponent {
    private _heading : string = "Passionate. Involved. Dedicated.";
}
<section id="section-about" class="section section-gap about">
    <div class="row">
        <img class="about-img" src="./assets/jb-icon1.png">
    </div>
    <div class="about-header">
        <h2 class="teal">PASSIONATE. <em class="dark-blue">INVOLVED.</em> DEDICATED.</h2>
    </div>
    <div class="about-description">
        <p>I am an extremely motivated Chicago-based developer
        immersed in the potential of computers since the ripe age of seven.
        Always consumed by the latest hardware and software trends,
        I live and breathe to <b><em class="dark-blue">push the limits</em></b> 
        of what people think apps can do.</p>
    </div>
</section>

// src/components/About.vue
<template>
  <section>
    <div class="about">
      <div class="about-img">
        <img
          title="I prefer Spaces over Tabs"
          alt="A floating astronaut in space on a laptop programming"
          src="../assets/Astronaut.png"
        />
      </div>
      <div>
        <h2 class="section-header">Hello</h2>
        <div class="section-subheader">Passionate. Involved. Dedicated.</div>
        <p class="section-description">
          I am an extremely motivated Chicago-based developer immersed in the
          potential of computers since the ripe age of seven. Always consumed by
          the latest hardware and software trends, I live and breathe to push
          the limits of what people think apps can do.
        </p>
      </div>
    </div>
  </section>
</template>

<script>
export default {
  name: "About",
};
</script>

<style lang="scss" scoped>
.about {
  display: flex;
  flex-direction: column;
  margin: 60px 40px;
}

.about-img {
  display: flex;
  justify-content: center;
  align-items: center;

  img {
    width: 60%;
  }
}
</style>
